# Generated by Django 4.2.4 on 2023-09-05 06:06

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', phone_field.models.PhoneField(max_length=31)),
                ('desc', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('avatar', models.ImageField(upload_to='')),
                ('phone', phone_field.models.PhoneField(max_length=31)),
                ('job_profile', models.CharField(max_length=50)),
                ('url1', models.URLField(max_length=50)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
