# Generated by Django 4.2.4 on 2023-09-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kulfi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kulfi_name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=300)),
                ('kulfi_pic', models.ImageField(upload_to='')),
                ('ingredients', models.CharField(max_length=300)),
                ('likes', models.IntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='static/avatar.png', upload_to='profile_pics/'),
        ),
    ]
