# Generated by Django 4.2.4 on 2023-09-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_kulfi_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kulfi',
            name='desc',
            field=models.TextField(),
        ),
    ]
