# Generated by Django 4.2.4 on 2023-09-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_kulfi_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kulfi',
            name='kulfi_pic',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
